import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

import { useLocale, useTranslations } from "next-intl";
import { notFound } from "next/navigation";
import React from "react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  const t = useTranslations("Navigation");

  return (
    <html lang={locale}>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar
            props={{
              homepage: t("homepage"),
              aboutMeHeader: t("aboutMe.title"),
              whoAmI: t("aboutMe.whoAmI"),
              skills: t("aboutMe.skills"),
              projects: t("aboutMe.projects"),
              locale: { locale },
            }}
          />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
